# Introduction

This workshop covers the basics of using Git to track and record changes to 
files on your local computer. This allows you to compare versions over time, 
recall earlier changes you made, and effectively collaborate on writing code and 
documents.

This is a **hybrid workshop**. First, independently work through this online 
tutorial at your own pace and **ensure that you have successfully installed Git **
**on your local computer**. Next, join us for the live interactive session 
(details below), during which we will use the Git Version Control System to 
learn and practice how to manage files on our local computer and work with Git. 
If you need help troubleshooting your installation, drop-in to [DataLab's virtual office hours ](https://datalab.ucdavis.edu/office-hours/) prior to the interactive 
session to ensure that you will be able to follow along on your own machine.

The full workshop description can be found [here](https://datalab.ucdavis.edu/eventscalendar/introduction-to-version-control-with-git-2/).

## Interactive Session Information

The workshop includes a live, interactive session to be held via Zoom on 
**Wednesday, February 15, 2021 from 3:00 pm to 5:00 pm**. Zoom login information 
will be sent to all registered participants via email; reach out to [datalab-training@ucdavis.edu](mailto:datalab-training@ucdavis.edu) the day prior 
if you received a registration confirmation but have not received your Zoom link.

## About this Tutorial

This online tutorial provides background information that will help participants 
to better understand the concepts introduced during the interactive session. 
It also includes information to help you successfully install Git on your local 
computer, **which must be completed prior to the interactive session**.


## Learning Objectives

1. Describe the history of version control systems (VCS), including their value
and function
2. Explain how a VCS manges files on your computer
3. Successfully install and run Git on your local computer
4. Interact with Git via your computer's command line
5. Successfully create local repositories and place your files under version control
6. Compare multiple versions of the same file and roll back to earlier versions
7. Perform basic branching and merging operations
8. Identify where to go to learn more



