# Common code to run before knitting each chapter.

url <- "img/mac_finder_1.png"
url2 <- "img/mac_window_2.png"
url3 <- "img/spoke_and_where_cloud.png"
url4 <- "img/distributed_network.png"
url5 <- "img/hybrid_network.png"
url6 <- "img/empty_sectors.png"
url7 <- "img/filled_bits.png"
url8 <- "img/directory.png"
url9 <- "img/mac_finder_3.png"
url10 <- "img/version_tree.png"
url11 <- "img/TT_tree_mobile.jpg"
url12 <- "img/mac_terminal.png"
url13 <- "img/bash.png"
url14 <- "img/GIT-Branchand-its-Operations.png"
url15 <- "img/datalab-logo-full-color-rgb.png"
url16 <- "img/save_stage_commit.png"
url17 <- "img/git_for_teams.png"
url18 <- "img/branching_workflows.png"
url19 <- "img/win_git_install_1_browser.png"
url20 <- "img/win_git_install_2_git page.png"
url21 <- "img/win_git_install_3_downloading.png"
url22 <- "img/win_git_install_4_run_open.png"
url23 <- "img/win_git_install_5_allow_changes.png"
url24 <- "img/win_git_install_6_license.png"
url25 <- "img/win_git_install_7_install_location.png"
url26 <- "img/win_git_install_8_default_components.png"
url27 <- "img/win_git_install_9_checked_components.png"
url28 <- "img/win_git_install_10_start_menu.png"
url29 <- "img/win_git_install_11_editor.png"
url30 <- "img/win_git_install_12_initial_branch.png"
url31 <- "img/win_git_install_13_path.png"
url32 <- "img/win_git_install_14_HTTPS_openssl.png"
url33 <- "img/win_git_install_15_line_ending.png"
url34 <- "img/win_git_install_16_terminal_emulator.png"
url35 <- "img/win_git_install_17_git_pull.png"
url36 <- "img/win_git_install_18_credential_helper.png"
url37 <- "img/win_git_install_19_extra_options.png"
url38 <- "img/win_git_install_20_experimental_options.png"
url39 <- "img/win_git_install_21_install_progress.png"
url40 <- "img/win_git_install_22_install_complete.png"
url41 <- "img/win_git_install_23_deslect_and_finish.png"

library(knitr)
