# Common code to run before knitting each chapter.

url <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/mac_finder_1.png"
url2 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/mac_window_2.png"
url3 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/spoke_and_where_cloud.png"
url4 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/distributed_network.png"
url5 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/hybrid_network.png"
url6 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/empty_sectors.png"
url7 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/filled_bits.png"
url8 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/directory.png"
url9 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/mac_finder_3.png"
url10 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/version_tree.png"
url11 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/TT_tree_mobile.jpg"
url12 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/mac_terminal.png"
url13 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/bash.png"
url14 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/GIT-Branchand-its-Operations.png"
url15 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/datalab-logo-full-color-rgb.png"
url16 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/save_stage_commit.png"
url17 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/git_for_teams.png"
url18 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/branching_workflows.png"
url19 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_1_browser.png"
url20 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_2_git page.png"
url21 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_3_downloading.png"
url22 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_4_run_open.png"
url23 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_5_allow_changes.png"
url24 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_6_license.png"
url25 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_7_install_location.png"
url26 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_8_default_components.png"
url27 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_9_checked_components.png"
url28 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_10_start_menu.png"
url29 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_11_editor.png"
url30 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_12_initial_branch.png"
url31 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_13_path.png"
url32 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_14_HTTPS_openssl.png"
url33 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_15_line_ending.png"
url34 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_16_terminal_emulator.png"
url35 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_17_git_pull.png"
url36 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_18_credential_helper.png"
url37 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_19_extra_options.png"
url38 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_20_experimental_options.png"
url39 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_21_install_progress.png"
url40 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_22_install_complete.png"
url41 <- "https://datalab.ucdavis.edu/cstahmer/git_workshop_images/win_git_install_23_deslect_and_finish.png"

library(knitr)
